// search
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'

// setting
export const UPDATE_THEME = 'UPDATE_THEME'
export const UPDATE_FONT_STYLE = 'UPDATE_FONT_STYLE'
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE'
