// search
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'

// setting
export const UPDATE_THEME = 'UPDATE_THEME'
export const UPDATE_FONT_FAMILY = 'UPDATE_FONT_FAMILY'
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE'
export const UPDATE_LINE_HEIGHT = 'UPDATE_LINE_HEIGHT'

// auth
export const UPDATE_TOKEN = 'UPDATE_TOKEN'
